// Code generated by Kitex v0.10.3. DO NOT EDIT.

package lepaudit

import (
	lep_audit "bupt/lep_audit/kitex_gen/lep_audit"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Audit(ctx context.Context, req *lep_audit.AuditReq, callOptions ...callopt.Option) (r *lep_audit.AuditResp, err error)
	CreateAudit(ctx context.Context, req *lep_audit.CreateAuditReq, callOptions ...callopt.Option) (r *lep_audit.CreateAuditResp, err error)
	AuditList(ctx context.Context, req *lep_audit.AuditListReq, callOptions ...callopt.Option) (r *lep_audit.AuditListResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kLepAuditClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kLepAuditClient struct {
	*kClient
}

func (p *kLepAuditClient) Audit(ctx context.Context, req *lep_audit.AuditReq, callOptions ...callopt.Option) (r *lep_audit.AuditResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Audit(ctx, req)
}

func (p *kLepAuditClient) CreateAudit(ctx context.Context, req *lep_audit.CreateAuditReq, callOptions ...callopt.Option) (r *lep_audit.CreateAuditResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAudit(ctx, req)
}

func (p *kLepAuditClient) AuditList(ctx context.Context, req *lep_audit.AuditListReq, callOptions ...callopt.Option) (r *lep_audit.AuditListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AuditList(ctx, req)
}
